### ISSUE TITLE
port to https://github.com/erthink/libmdbx also?

### ISSUE THREAD

**Issue by hiqsociety** [LumoSQL/lumosql#4] opened 2021-03-18 04:43 UTC
possible to include libmdbx in the port?

**Comment by danshearer** [comment] 2021-03-18 07:48
It would certainly be possible, because as far as I understand it there is no significant difference between LMDB and libmdbx. Does this match what you see?

That means that issues we had to solve such as the use of 32-bit keys by LMDB and inability to upgrade a transaction from RO to RW will be the same as for LMDB.

Right now I'm looking at K-V stores in C that implement other approaches, such as Adapative Radix Trees and Fractal Trees. Modern hardware and OSs mean that tree store designs from the 20th century need to be revisited.

Would you like to help out with the LMDB/libmdbx port by trying it out and looking at the user interface (PRAGMAs etc) in SQLite?

**Comment by danshearer** [comment] 2021-03-18 07:48
Didn't mean to close :-)

**Comment by likern** [comment] 2021-05-10 02:41
@danshearer Have you found any of those databases? Could you recommend such a literature about Radix Trees and Fractal Trees?

**Comment by danshearer** [comment] 2021-05-11 09:09
> @danshearer Have you found any of those databases? 

Yes I have. I will tell you here where we are up to, but we need your help because it is a large task.

I have had the pleasure of working with [Karl Malbrain](https://github.com/malbrain) on his implementation of Blink Trees. As of a few days ago, the following commands will build a program called "standalone" which is a demonstrator of two types of indexing: Blink (ie Btrees with Blink concurrency) and Adaptive Radix trees:

```bash
git clone https://github.com/malbrain/database
cd database
git clone https://github.com/malbrain/rwlock
git clone https://github.com/malbrain/Hi-Performance-Timestamps
git clone https://github.com/malbrain/mutex
# from now on, 'git clone --recurse' will work in the database directory
# for updates if Karl has pushed any
rm -rf alpha/   # this isn't meant to be here any more
sh ./build
```
The README contains a terse description of what the demonstration program is supposed to do, and so far the code appears to follow the theory. This has definitely not been incorporated into LumoSQL, but it is a potential candidate. I'm sure Karl would consider any pull requests for documentation.

> Could you recommend such a literature about Radix Trees and Fractal Trees?

First I recommend you try something simpler, but still not simple: learn about modern locking and latches in Btrees using the Blink algorithms. And for this we have not only Karl's work, but also production Postgres code. Here is some reading, all of which is freely available online:

* Classic Btrees. There are many sources for this, it's standard compsci. They are implemented in all three backends that LumoSQL supports today: classic SQLite; LMDB and BDB.
* The original Blink paper: P. Lehman and S. Yao, Efficient Locking for Concurrent Operations on B-Trees, ACM Transactions on Database Systems, Vol 6, No. 4, December 1981, pp 650-670
* A follow paper that filled in details, especially node deletion: V. Lanin and D. Shasha, A Symmetric Concurrent B-Tree Algorithm, Proceedings of 1986 Fall Joint Computer Conference, pp 380-389
* Postgres nbtree: The foregoing Blink algorithm papers are great, but they are not an implementation. Postgres [nbtree](https://github.com/postgres/postgres/tree/c30f54ad732ca5c8762bb68bbe0f51de9137dd72/src/backend/access/nbtree) is an implementation which adds constraints for concurrency in a real-world database, and an additional traversal mode, among other things. 
* Karl Malbrain's [Concurrency Paper](https://www.researchgate.net/publication/46585073_A_Blink_Tree_latch_method_and_protocol_to_support_synchronous_node_deletion) and his code discussed above implements the Lehman & Yao plus the Lannin & Sasha algorithms, but abstracts out the node locking mechanism to operating system primitives. (This PDF cannot be read by standalone open source PDF viewers that I have found, but is rendered by in-browser viewers in Firefox and Chrome.)

All of the above is about improving concurrent access while still maintaining database guarantees. It also does not really take us out of the 20th century. In the 21st century, many things have changed which means algorithms need to change. Some of the new factors include: SSD hardware preferring larger block sizes; relative access times between primary and secondary storage are smaller; 21st century L1 cache sizes are immensely larger; on-chip parallelism is immense; on-chip asymmetry is becoming more common; network bandwidth is much higher even on embedded nodes; network latency can be much lower.

To accommodate 21st century needs we need to look at changes. The ones LumoSQL has identified so far are:
* Single level store. This is a 20th century concept (apparently in Multics??) but is only implemented in LMDB that I know of. This is at a lower level than tree algorithms. LMDB implements a more-or-less classic btree. So we started with LMDB, as you know.
* Fractal Trees. As a start you can study the code and related papers around Tokutek, whose code is in MongoDB. We're still working through this. (What might seem to be a software patent problem with fractal trees appears so far not to be an issue.)

Since LumoSQL is trying to be a working reference platform as well as an experimental testbed, these questions are very much about real-world applications.

You can help by contributing what you have learned, and any codebases that we have overlooked.

Would you be willing to try out the LumoSQL benchmarking tool and let us know the results from your setup?

**Comment by erthink** [comment] 2021-05-28 14:45
FYI.
[Erigon](https://github.com/ledgerwatch/erigon) (one of the most efficient frontiers for Ethereum) recently switched from LMDB to MDBX.
AFAIK, there was no single reason, but because are a set of [MDBX's improvements over LMDB](https://github.com/erthink/libmdbx#improvements-beyond-lmdb).
Regards.

**Comment by vorot93** [comment] 2021-05-30 17:23
@danshearer I can confirm that we at Erigon have switched to MDBX and solved multiple longstanding issues we had with LMDB.

**Comment by AlexeyAkhunov** [comment] 2021-05-30 19:57
> [Erigon](https://github.com/ledgerwatch/erigon) (one of the most efficient frontiers for Ethereum) recently switched from LMDB to MDBX.
> AFAIK, there was no single reason, but because are a set of [MDBX's improvements over LMDB](https://github.com/erthink/libmdbx#improvements-beyond-lmdb).

We have listed the main reasons here, hope this is helpful: https://github.com/ledgerwatch/erigon/wiki/Criteria-for-transitioning-from-Alpha-to-Beta#switch-from-lmdb-to-mdbx

**Comment by hyc** [comment] 2021-07-23 13:11
@AlexeyAkhunov your post says "usage of LMDB that was not envisaged by the creators" - I don't recall you have ever communicated any such issues to us. Did you submit any bug reports or send any emails to the openldap-technical mailing list?

**Comment by AlexeyAkhunov** [comment] 2021-07-23 20:16
> @AlexeyAkhunov your post says "usage of LMDB that was not envisaged by the creators" - I don't recall you have ever communicated any such issues to us. Did you submit any bug reports or send any emails to the openldap-technical mailing list?

Hi Howard, thank you for making LMDB, we had great experience with it, and we are still using its derivative.

I remember asking for your comments when I wrote this analysis: https://github.com/ledgerwatch/erigon/wiki/LMDB-freelist-illustrated-guide , not sure where it was (perhaps on Twitter). I am sorry I made assumptions that these won't be fixed, but by that time I decided to patch LMDB anyway to mitigate some of the issues our users were experiencing, and the patch worked somewhat, we got rid of the most serious symptoms (very slow commits due to large freelists). But there were other compelling reasons to switch to MDBX, and we did a lot of work (several months) to iron out all the issues, and now it is done.

**Comment by hyc** [comment] 2021-07-23 21:05
Twitter is not a support channel, so in all likelihood I never saw it.

Good luck with your project.

**Comment by hyc** [comment] 2021-07-23 21:10
Obtw, to answer your question about why the freelist is sorted in reverse order: we preferentially use pages in ascending order, and it's easier to truncate one element off the end of an array than to take it off the head of the array and be forced to slide everything else down before shrinking it. You would have gotten this answer a long time ago if you had actually asked in an OpenLDAP support channel.

**Comment by vorot93** [comment] 2021-07-23 21:13
@hyc you see, this is also one of the reasons we went with MDBX - its author being far more accessible and less abrasive.

**Comment by AlexeyAkhunov** [comment] 2021-07-23 21:21
> Twitter is not a support channel, so in all likelihood I never saw it.
> 
> Good luck with your project.

Thank you. I think you actually responded on Twitter :) But I have no qualms with you or LMDB, we just decided to move on. Oh, and to the question about the reverse order, I suppose it wasn't really important, I just noticed it when I was analysing the data file. So no worries. I managed to get all the answered I needed from the code.

**Comment by hyc** [comment] 2021-07-23 22:15
@vorot93 What did I say that was abrasive? Merely stating facts - if you want to make sure your questions get answered, you have to submit them in forum that's actually tracked. That's why we have bug trackers and mailing lists.

**Comment by danshearer** [comment] 2022-08-30 07:46
LumoSQL has moved along plenty since this was opened, with the last 7 years worth of LMDB. We haven't tried with libmdbx yet, but if someone would like to help with that then fine (I gather the API is identical or near-identical.)

**Closed as completed by danshearer** 2022-08-30 07:46 UTC
